name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # --------------------------------------
  # JOB 1: Install dependencies & Lint
  # --------------------------------------
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Adjust if needed

      # Install dependencies for server
      - name: Install server dependencies
        run: |
          cd server
          npm install

      # Install dependencies for client
      - name: Install client dependencies
        run: |
          cd client
          npm install

      # Run ESLint (fails if lint issues remain)
      - name: Run Lint Check
        run: npm run lint

  # --------------------------------------
  # JOB 2: Security Audit
  # --------------------------------------
  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-lint  # Only runs after linting succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Check server dependencies for vulnerabilities
      - name: Audit server dependencies
        run: |
          cd server
          npm audit --production

      # Check client dependencies for vulnerabilities
      - name: Audit client dependencies
        run: |
          cd client
          npm audit --production

  # --------------------------------------
  # JOB 3: CodeQL Static Analysis 
  # --------------------------------------
  codeql-analysis:
    runs-on: ubuntu-latest
    needs: security-scan  # Only runs after lint & security checks pass
    permissions:
      security-events: write
      contents: read
      actions: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: javascript-typescript
            build-mode: none  # Adjust if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initialize CodeQL analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      # Run CodeQL analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
