name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # --------------------------------------
  # JOB 1: Install dependencies & Lint
  # --------------------------------------
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # Adjust version if needed

      # Install dependencies for both server & client
      - name: Install dependencies (server)
        run: |
          cd server
          npm install

      - name: Install dependencies (client)
        run: |
          cd client
          npm install

      # Fix ESLint permissions issue
      - name: Fix ESLint Permissions
        run: chmod +x node_modules/.bin/eslint || true

      # Run ESLint to check for code quality issues
      - name: Run ESLint
        run: npx eslint . || true  # '|| true' ensures the pipeline continues even if lint fails

  # --------------------------------------
  # JOB 2: Security Scan (npm audit)
  # --------------------------------------
  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-lint  # Only runs after linting succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Run npm audit on both client & server
      - name: Audit server dependencies
        run: |
          cd server
          npm audit --production || true  # Continue even if audit finds vulnerabilities

      - name: Audit client dependencies
        run: |
          cd client
          npm audit --production || true  # Continue even if audit finds vulnerabilities

  # --------------------------------------
  # JOB 3: CodeQL Security Analysis (Optional)
  # --------------------------------------
  codeql-analysis:
    runs-on: ubuntu-latest
    needs: security-scan  # Only runs after lint & security checks pass
    permissions:
      security-events: write
      contents: read
      actions: read
      packages: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: javascript-typescript
            build-mode: none  # Adjust if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Initialize CodeQL analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      # Run CodeQL analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"
