# .github/workflows/nodejs-ci.yml

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # Adjust the Node versions as needed

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v4

      # 2) Set up Node for the given version, but do NOT enable the built-in cache
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 3) Install + test for "server" subfolder
      - name: Install server dependencies
        run: |
          cd server
          npm ci

      - name: Build and test server
        run: |
          cd server
          npm run build --if-present
          npm test

      # 4) Install + test for "client" subfolder
      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Build and test client
        run: |
          cd client
          npm run build --if-present
          npm test
